version: '3'
services:
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "5000:5000"
  message_service:
    build: ./message_service
    container_name: message_service
    ports:
      - "5001:5001"
    depends_on:
      - user_service
  like_service:
    build: ./like_service
    container_name: like_service
    ports:
      - "5002:5002"
